import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {resolve} from 'node:path';
const require=createRequire(resolve(process.argv[2],'package.json'));
const {PGlite}=require('@electric-sql/pglite');
const db=new PGlite();
await db.exec(`CREATE ROLE anon;CREATE ROLE authenticated;CREATE ROLE service_role BYPASSRLS;
CREATE TABLE netflix_accounts(email text PRIMARY KEY,netflix_id text,secure_netflix_id text,plan text,status text);
CREATE TABLE access_keys(code text PRIMARY KEY,assigned_email text);
INSERT INTO netflix_accounts VALUES('a','fake-a','','Basic','live'),('b','fake-b','','Premium','blocked_for_new_assignments'),('c','fake-c','','Premium','live');
INSERT INTO access_keys VALUES('SAFE','c');`);
const sql=await readFile(new URL('../../supabase/migrations/20261009162315_inventory_jobs.sql',import.meta.url),'utf8');
await db.exec(sql);await db.exec(sql);
for(const role of ['anon','authenticated']) {
 await db.exec(`SET ROLE ${role}`);
 await assert.rejects(db.query('SELECT inventory_progress(NULL)'),/permission denied/);
 await assert.rejects(db.query('SELECT * FROM inventory_items'),/permission denied/);
 await db.exec('RESET ROLE');
}
await db.exec('GRANT SELECT,INSERT,UPDATE,DELETE ON netflix_accounts TO service_role;GRANT SELECT,UPDATE ON access_keys TO service_role;SET ROLE service_role');
async function call(name,args) {return (await db.query(`SELECT inventory_${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) AS data`,args)).rows[0].data;}
assert.equal((await call('enqueue',['run1','full_scan'])).existing,false);
assert.deepEqual(await call('enqueue',['run2','payment_scan']),{id:'run1',existing:true});
const a=await call('claim',['worker1']);const b=await call('claim',['worker2']);const c=await call('claim',['worker3']);
assert.notEqual(a.id,b.id);assert.equal(await call('claim',['worker4']),null);
assert.equal(await call('finish',[a.id,'wrong','DIE',null]),false);
assert.equal(await call('finish',[a.id,'worker1','LIVE',null]),true);
assert.equal((await db.query("SELECT plan FROM netflix_accounts WHERE email='a'")).rows[0].plan,'Basic');
assert.equal(await call('finish',[b.id,'worker2','LIVE','Premium']),true);
assert.equal((await db.query("SELECT status FROM netflix_accounts WHERE email='b'")).rows[0].status,'blocked_for_new_assignments');
await db.exec("UPDATE inventory_items SET lease_until=now()-interval '1 second' WHERE email='c'");
assert.equal(await call('finish',[c.id,'worker3','DIE',null]),false);
const reclaimed=await call('claim',['newworker']);assert.equal(reclaimed.id,c.id);
assert.equal(await call('finish',[c.id,'worker3','DIE',null]),false);
assert.equal(await call('finish',[c.id,'newworker','DIE',null]),true);
const p=await call('progress',['run1']);assert.equal(p.processed,3);assert.equal(p.run.status,'completed');
assert.equal((await db.query("SELECT status FROM netflix_accounts WHERE email='c'")).rows[0].status,'needs_review');
assert.equal((await db.query("SELECT assigned_email FROM access_keys WHERE code='SAFE'")).rows[0].assigned_email,'c');
assert.ok(!JSON.stringify(p).includes('fake-a'));assert.ok(!JSON.stringify(p).includes('lease_token'));
await call('enqueue',['run3','full_scan']);const changed=await call('claim',['change']);
await db.exec("UPDATE netflix_accounts SET netflix_id='new-cookie' WHERE email='a'");
await call('finish',[changed.id,'change','DIE',null]);
assert.equal((await call('progress',['run3'])).counts.CHANGED,1);
while(true) { const item=await call('claim',['drain']);if(!item)break;await call('finish',[item.id,'drain','LIVE',null]); }
await call('enqueue',['import1','import',JSON.stringify([{email:'new',netflix_id:'synthetic-new',secure_netflix_id:''}])]);
const imported=await call('claim',['importer']);
assert.equal(imported.netflix_id,'synthetic-new');
await call('finish',[imported.id,'importer','LIVE','Basic']);
assert.equal((await db.query("SELECT plan FROM netflix_accounts WHERE email='new'")).rows[0].plan,'Basic');
assert.equal((await db.query("SELECT payload FROM inventory_items WHERE run_id='import1'")).rows[0].payload,null);
await db.exec("UPDATE netflix_accounts SET netflix_id='same' WHERE email IN ('b','c');UPDATE access_keys SET assigned_email='b, c';INSERT INTO netflix_accounts VALUES('d','same','','Premium','live')");
await call('enqueue',['duplicates','duplicates']);
while(true) { const item=await call('claim',['dup']);if(!item)break;await call('finish',[item.id,'dup','KEPT',null]); }
assert.equal((await db.query("SELECT count(*) AS n FROM netflix_accounts WHERE email IN ('b','c')")).rows[0].n,2);
assert.equal((await db.query("SELECT count(*) AS n FROM netflix_accounts WHERE email='d'")).rows[0].n,0);
await call('enqueue',['retry','full_scan']);
const retry=await call('claim',['retry0']);
await call('finish',[retry.id,'retry0','UNKNOWN',null]);
assert.equal((await call('progress',['retry'])).processed,0);
await db.exec("UPDATE inventory_items SET lease_until=now()-interval '1 second' WHERE status='pending'");
const second=await call('claim',['retry1']);assert.equal(second.id,retry.id);
await call('finish',[second.id,'retry1','UNKNOWN',null]);
await db.exec("UPDATE inventory_items SET lease_until=now()-interval '1 second' WHERE status='pending'");
const third=await call('claim',['retry2']);assert.equal(third.id,retry.id);
await call('finish',[third.id,'retry2','UNKNOWN',null]);
assert.equal((await call('progress',['retry'])).counts.UNKNOWN,1);
console.log('Inventory migrations: privileges, leases, retries, progress and protected links passed');
await db.close();
